CREATE DATABASE Ristorante;

CREATE TABLE Ristorante.Menu(
    Nome_piatto     VARCHAR(30) PRIMARY KEY, 
    Categoria       VARCHAR(20),
    Ingredienti     VARCHAR(150),
    Fine_cottura    VARCHAR(50),
    Prezzo          FLOAT
);

INSERT INTO Ristorante.Menu (Nome_piatto, Categoria, Ingredienti, Fine_cottura, Prezzo) VALUES

--PIZZE-CLASSICHE--
("Bufala","pizze-classiche","bufala, pomodoro, origano, basilico","origano, basilico",9),
("Capricciosa con salamino","pizze-classiche","mozzarella, pomodoro, carciofi, prosciutto cotto, champignon trifolati, salamino","",9.5),
("Diavola","pizze-classiche","mozzarella, pomodoro, salamino","",8),
("Funghi","pizze-classiche","mozzarella, pomodoro, funghi","",8),
("Salsiccia e origano","pizze-classiche","mozzarella, pomodoro, salsiccia, origano","",8),
("Margherita","pizze-classiche","mozzarella, pomodoro","",7),
("Margherita con patate fritte","pizze-classiche","mozzarella, pomodoro, patate fritte","patate fritte",8.5),
("Ortolana","pizze-classiche","mozzarella, pomodoro, peperoni, melanzane, zucchine","",8.5),
("Parigina","pizze-classiche","mozzarella, pomodoro, crudo","crudo",9.5),
("Prosciutto e funghi","pizze-classiche","mozzarella, pomodoro, prosciutto cotto, funghi","",9),
("Prosciutto cotto","pizze-classiche","mozzarella, pomodoro, prosciutto cotto","",9),
("Pugliese","pizze-classiche","mozzarella, pomodoro, cipolla","",7.5),
("Quattro formaggi","pizze-classiche","gorgonzola, brie, scamorza, bufala","",9),
("Quattro stagioni","pizze-classiche","mozzarella, pomodoro, carciofi, olive, prosciutto cotto, funghi","",9),
("Speck","pizze-classiche","mozzarella, pomodoro, speck","speck",9),
("Tirolese","pizze-classiche","mozzarella, pomodoro, wurstel, salamino","wurstel salamino",9),
("Tonno e cipolla","pizze-classiche","mozzarella, pomodoro, tonno, cipolla","",8.5),
("Tre peccati","pizze-classiche","mozzarella, pomodoro, cipolla, salsiccia, peperoni","",9),
("Tonno","pizze-classiche","mozzarella, pomodoro, tonno","",8.5),
("Wurstel","pizze-classiche","mozzarella, pomodoro, wurstel","",8),
("Wurstel e patatine","pizze-classiche","mozzarella, pomodoro, wurstel, patatine fritte","patatine fritte",9),
("Radicchio e gorgonzola","pizze-classiche","mozzarella, pomodoro, radicchio, gorgonzola","",8.5),
("Speck e gorgonzola","pizze-classiche","mozzarella, pomodoro, speck, gorgonzola","speck",9),

--PIZZE-ROSSE--
("Bombarda","pizze-rosse","mozzarella, pomodoro, salsiccia, gorgonzola, cipolla, fagioli","",11),
("Boscaiola","pizze-rosse","mozzarella, pomodoro, funghi, formaggio Asiago, speck, ricotta affumicata","speck, ricotta affumicata",11),
("Delicata","pizze-rosse","mozzarella, pomodoro, brie, speck, pomodorini","speck, pomodorini",10),
("Brontolo","pizze-rosse","mozzarella, pomodoro, salamino, olive, peperoncino, pomodorini, stracciatella, basilico","pomodorini, stracciatella, basilico",10.5),
("Cazzarola","pizze-rosse","mozzarella, pomodoro, porcini, burrata, rucola, pomodorini","burrata, rucola, pomodorini",11),
("Dedicata a te","pizze-rosse","mozzarella, pomodoro, salamino, origano, pomodorini, stracciatella, basilico","pomodorini, stracciatella, basilico",10.5),
("DOC","pizze-rosse","mozzarella, pomodoro, grana, melanzane, crudo","crudo",11),
("Franca","pizze-rosse","mozzarella, pomodoro, grana, melanzane, crudo","crudo",11),
("La focosa","pizze-rosse","mozzarella, pomodoro, gorgonzola, cipolla, aglio, acciughe, origano, peperoncino, salamino","",11),
("La vera caprese","pizze-rosse","mozzarella, pomodoro, olio, pomodoro a fette, pomodorini, bufala, origano, basilico","pomodoro a fette, pomodorini, bufala, origano, basilico",11.5),
("Languida","pizze-rosse","mozzarella, pomodoro, formaggio Asiago, zucchine, porchetta","porchetta",10),
("Meritevole","pizze-rosse","mozzarella, pomodoro, peperoncino, basilico, burrata, pomodorini","basilico, burrata, pomodorini",11.5),
("Panoramica","pizze-rosse","mozzarella, pomodoro, burrata, speck","burrata, speck",11),
("Millo","pizze-rosse","mozzarella, pomodoro, burrata, crudo","burrata, crudo",12),
("Odorosa","pizze-rosse","mozzarella, pomodoro, uovo, pancetta, salsiccia, gorgonzola, olive","uovo",11),
("Padana","pizze-rosse","mozzarella, pomodoro, stracchino, zucchine, grana, crudo","crudo",10.5),
("Piacevole","pizze-rosse","mozzarella, pomodoro, crudo, pomodorini","crudo, pomodorini",10.5),
("Maialona","pizze-rosse","mozzarella, pomodoro, gorgonzola, pancetta, burrata","gorgonzola, pancetta, burrata",11),
("Mediterranea","pizze-rosse","mozzarella, pomodoro, acciughe, olive, origano, pomodori secchi, gorgonzola, capperi, salamino, peperoni","",11.5),
("Meravigliosa","pizze-rosse","pomodoro, formaggio Asiago, brie, scamorza, pomodorini, porchetta, stracciatella","pomodorini, porchetta, stracciatella",11.5),
("Rosmarino","pizze-rosse","mozzarella, pomodoro, rosmarino, capperi, pomodorini siciliani, olive","",10),
("Salsicciona","pizze-rosse","mozzarella, pomodoro, radicchio, salsiccia, grana","grana",10),
("Sboldra","pizze-rosse","mozzarella, pomodoro, grana, salamino, olio all'aglio, rosmarino","",10.5),
("Tatiana","pizze-rosse","mozzarella, pomodoro, melanzane, pomodorini, basilico, crudo, burrata","pomodorini, basilico, crudo, burrata",12),
("Treviso Treviso","pizze-rosse","mozzarella, pomodoro, gorgonzola, radicchio, crudo, grana","crudo, grana",11),
("Vegetariana","pizze-rosse","mozzarella, pomodoro, melanzane, peperoni, pomodoro a fette, origano, rucola, grana","rucola, grana",10),
("Gradevole","pizze-rosse","mozzarella, pomodoro, pesto, olive, peperoncino, pomodorini, basilico","pomodorini, basilico",10),
("Rosamunda","pizze-rosse","mozzarella, pomodoro, paté di basilico, rucola, pomodorini, burrata","rucola, pomodorini, burrata",10),
("Romeo e Giulietta","pizze-rosse","mozzarella, pomodoro, pesto, feta greca, pomodorini, basilico","pomodorini, basilico",10.5),
("Super Sic","pizze-rosse","mozzarella, pomodoro, paté di carciofi, pomodoro a fette, zucchine, crudo","",11.5),

--PIZZE-BIANCHE--
("Albatros","pizze-bianche","mozzarella, radicchio, olive, porchetta","porchetta",10.5),
("Bambi","pizze-bianche","mozzarella, formaggio Asiago, porcini, champignon, funghi, grana","",10.5),
("Betty","pizze-bianche","mozzarella, pancetta, patate, rosmarino","pancetta, patate, rosmarino",10.5),
("Black","pizze-bianche","mozzarella, scamorza, gorgonzola, ricotta affumicata, crudo","ricotta affumicata, crudo",11),
("Cip Ciop","pizze-bianche","mozzarella, brie, burrata, pomodorini, crudo","burrata, pomodorini, crudo",11),
("Estate","pizze-bianche","mozzarella, stracchino, crudo, pomodorini, rucola","crudo, pomodorini, rucola",10.5),
("Incatenata","pizze-bianche","formaggio Asiago, funghi, radicchio, burrata, porchetta","burrata, porchetta",11),
("La cruda","pizze-bianche","mozzarella, rucola, pomodorini, crudo, bufala stracciata","rucola, pomodorini, crudo, bufala stracciata",12.5),
("Pancio speck","pizze-bianche","mozzarella, pancetta, speck, grana, scamorza, carciofi, champignon,","speck, grana",11.5),
("Un sogno","pizze-bianche","mozzarella, porcini, rucola, salamino, speck, burrata","burrata",12.5),
("Che gusto","pizze-bianche","mozzarella, paté di carciofi, radicchio, burrata, speck","burrata, speck",11),
("Lory","pizze-bianche","mozzarella, crema ai quattro formaggi, gorgonzola, peperoni, pancetta","",10.5),
("Rodeo","pizze-bianche","mozzarella, porcini, paté di carciofi, radicchio, porchetta","porchetta",11),
("Saporita 2","pizze-bianche","mozzarella, crema ai quattro formaggi, champignon, speck, noci, grana","speck, noci, grana",11),
("Speckona","pizze-bianche","mozzarella, paté di carciofi, champignon, speck, grana","",10.5),

--HAMBURGHER--
("American Hustle","burger","cheddar, bacon, pomodoro a fette, cotoletta, uovo","cotoletta, uovo",14),
("Asiago","burger","pane e speck, salsiccia, formaggio, funghi","salsiccia, formaggio",14),
("Caesar","burger","pane e bacon, pollo, grana, lattuga, pomodoro a fette, salsa caesar","lattuga, salsa caesar",14),
("Challenger","burger","cheddar, doppio burger, pomodoro a fette, lattuga, bacon, anelli di cipolla","burger, lattuga, anelli di cipolla",19),
("Emperor","burger","burger, pomodoro a fette, uovo, lattuga, burrata","uovo, lattuga, burrata",14),
("Flavoursome","burger","pane e speck, burger, pomodorini, cipolla caramellata, crema ai quattro formaggi","burger",15),
("Italian","burger","melanzane, crema di melanzane, crudo, burger, mozzarella, lattuga, basilico","lattuga, burger",16),
("Original","burger","cheddar, bacon, burger, lattuga, pomodoro a fette","lattuga, burger",12.5),
("Porkacci","burger","burger, porchetta, burrata, crema ai pistacchi, cipolla caramellata, pomodoro a fette","burger, burrata",17),
("Salmon","donut burger","pane bagel, salmone, stracchino, pomodorini","salmone",16),
("Veggie","donut burger","pane bagel, burger, melanzane, pomodoro a fette","lattuga, burger",15),
("Vesuvio","colata burger","cheddar, burger, cipolla caramellata, fagioli neri, tabasco, salsa guacamole, jalapenos","lattuga, burger",18),
("Real Double","colata burger","cheddar, doppio burger, formaggio, pomodorini","burger",20),
("Smokin Trevi","smoki","radicchio, burger, porchetta, cipolla, formaggio","burger",18),
("Pulled Pork","smoki","pulled pork, funghi, cipolla, lattuga, crauti","pulled pork, lattuga",17),
("Classic Tartare","smoki","tartare, uovo, lattuga, pomodoro a fette","tartare, uovo, lattuga",18),

--CLUB-SANDWITCH--
("club-1","club-sandwich","bacon, mozzarella, uova, lattuga, pomodoro a fette","lattuga",11),
("club-2","club-sandwich","speck, crema ai quattro formaggi, formaggio Asiago, mozzarella, funghi, lattuga","lattuga",12),
("club-3","club-sandwich","pollo, cheddar, prosciutto cotto, mozzarella, uova, pomodoro a fette, lattuga, salsa caesar","lattuga, salsa caesar",12),
("club-4","club-sandwich","melanzane, zucchine, radicchio, peperoni, uova, mozzarella, formaggio Asiago, pomodoro a fette","",11.5),
("club-5","club-sandwich","burger, bacon, cheddar, uova, pomodoro a fette, lattuga, mozzarella, doppia cipolla caramellata","lattuga",13.5),
("club-6","club-sandwich","salmone, stracchino, pomodorini, salsa guacamole, mozzarella, lattuga","lattuga, salmone",14),
("club-7","club-sandwich","tartare, bufala, olive, mozzarella, uova, lattuga, pomodoro a fette","lattuga, tartar",14),
("club-8","club-sandwich","salsiccia, radicchio, crema ai quattro formaggi, doppia cipolla caramellata, mozzarella, lattuga","lattuga",12.5),
("club-9","club-sandwich","pulled pork, doppia cipolla caramellata e croccante, fagioli neri, cheddar, bacon, lattuga, pomodoro a fette","lattuga",13.5),

--BRUSCHETTE--
("Alfa","bruschette","mozzarella, pomodorini, basilico, olio","basilico",7),
("Beta","bruschette","aglio, pomodoro, origano","origano",5),
("Gamma","bruschette","pomodoro, mozzarella, origano","origano",6),
("Delta","bruschette","pomodoro, mozzarella, funghi, prosciutto cotto, origano","origano",7),
("Epsilon","bruschette","pomodoro, mozzarella, salamino piccante, origano","origano",6.5),
("Iota","bruschette","mozzarella, gorgonzola, speck, grana","speck, grana",8),

--CONCHAS--
("concha 0","conchas","mozzarella, pomodoro a fette, rucola, prosciutto cotto, grana","grana",9),
("concha 1","conchas","mozzarella, melanzane, peperoni, crudo","crudo",9),
("concha 3","conchas","mozzarella, porchetta, olio, sale, pepe, misticanza","misticanza",9),
("concha 6","conchas","mozzarella, formaggio Asiago, speck","speck",9),
("concha 9","conchas","mozzarella, brie, radicchio, pancetta","",9),
("concha 13","conchas","mozzarella, formaggio Asiago, zucchine, prosciutto cotto","",9),

--PIADINE E SCHIACCIATE--
("Marti","piadine","mozzarella, crudo","crudo",8),
("Miru","piadine","mozzarella, lattuga, porchetta","lattuga, porchetta",8),
("Ceci","piadine","stracchino, rucola, crudo","rucola, crudo",8.5),
("Sofi","piadine","formaggio Asiago, grana, zucchine, prosciutto cotto","grana",8),
("Jessi","piadine","mozzarella, salsiccia, peperoni, cipolla","",8),
("K1","schiacciate","olio, rosmarino","",5),
("K2","schiacciate","crudo","crudo",7.5),
("K3","schiacciate","mozzarella, pomodorini, basilico","pomodorini, basilico",7.5);